name: Tests-With-Pixi

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  tests-using-pixi:
    timeout-minutes: 10
    runs-on: ubuntu-22.04-gpu-t4
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: run nvidia-smi
      run: nvidia-smi

    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: "latest"
        run-install: false

    - name: Install pre-commit
      run: pixi global install pre-commit

    - name: Install dev environment using pixi
      run: pixi install --environment dev

    - name: Run tests
      run: pixi run --environment dev test

    - name: Run pre-commit hooks
      run: pixi run pre-commit-hooks
